### ISSUE TITLE
Terralith and Mountain Den

### ISSUE THREAD

**Issue by SiverDX** [Jusey1/Kobolds#1]
**Version**: Forge, 1.19.2 - 2.6.8

When using Terralith the structure becomes absurdly rare (sometimes too rare so it doesn't spawn at all, checked huge radiuses)

Only saw it one time: 
![image](https://github.com/Jusey1/Kobolds/assets/22003703/ca7ca80e-5fdc-4160-85bc-7b1f43696f82)
(Only using Kobolds!, Structure Essentials, Structure Gel API, JEI and Terralith here) 

I know it uses `#minecraft:is_mountain` but not sure if mountains are just that rare with Terralith... or there are other problems?
Also don't really know which biomes would fit the structure (so I could expand the list of biomes myself)

---

![image](https://github.com/Jusey1/Kobolds/assets/22003703/2219c1d8-02b0-406c-aa7e-a9b17b1f1d53)

**Comment by Jusey1** [comment]
Should /locate biome #is_mountain to check if it is a weird issue with Terra making mountains super rare or something.

**Comment by Jusey1** [comment]
Also, mind you, Kobold Structures will not place if the desired location is too close to ocean/river biomes and there is too much water within the area of it's desired location, which can lead to a failure placement. So take that into account as well.

**Comment by SiverDX** [comment]
> Also, mind you, Kobold Structures will not place if the desired location is too close to ocean/river biomes and there is too much water within the area of it's desired location, which can lead to a failure placement. So take that into account as well.

I suppose this creates some issues with Terralith generation then, the biomes themselves are there

**Comment by Jusey1** [comment]
Odd.
