### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by exdj158** [Jusey1/kobolds#1]
game version 1.19.2
forge 43.1.57
Kobolds-2.2.12
![image](https://user-images.githubusercontent.com/85820498/207903522-ae61cbdd-3a01-459f-843d-7e8604af4141.png)

**Comment by Jusey1** [comment]
Can I have an explanation of what was happening by chance in-game and the full logs?

**Comment by Jusey1** [comment]
Actually, regenerate the Kobolds config. I think I know what is happening and it seems like that it was trying to generate a structure with villagers in it but you didn't regenerate the Kobolds config after the most recent update that brought back the config for them to have a new AI goal in relation to kobolds.

**Comment by exdj158** [comment]
> Actually, regenerate the Kobolds config. I think I know what is happening and it seems like that it was trying to generate a structure with villagers in it but you didn't regenerate the Kobolds config after the most recent update that brought back the config for them to have a new AI goal in relation to kobolds.

thanks,i regenerate and now things have been okay
