### ISSUE TITLE
"Found a Loot Table path that does not exist" reported by Blame mod

### ISSUE THREAD

**Issue by ZXLLlong** [Jusey1/Kobolds#1]
Forge: 1.16.5-36.1.24
Kobolds!: V1.2

**What happened?**

I created a new world, wandered around in it, then a lag occurred and I immediately opened the log file and it showed the following:

```
[295月2021 01:58:30.244] [Server thread/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Report 1.16.5-3.0.2-forge ******************

 Found a Loot Table path that does not exist:  kobolds:entities/kobold
 The path represented by this Loot Table is:  data/kobolds/loot_tables/entities/kobold.json
 Loot Table method called at:  net.minecraft.entity.LivingEntity.func_213354_a
                               net.minecraft.entity.MobEntity.func_213354_a
 Most common cause is that the Loot Table file is not actually at that location.
 Please let the mod author know about this so they can check to see if their Loot Table is correct.

[295月2021 01:58:36.690] [Server thread/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Report 1.16.5-3.0.2-forge ******************

 Found a Loot Table path that does not exist:  kobolds:entities/kobold_zombie
 The path represented by this Loot Table is:  data/kobolds/loot_tables/entities/kobold_zombie.json
 Loot Table method called at:  net.minecraft.entity.LivingEntity.func_213354_a
                               net.minecraft.entity.MobEntity.func_213354_a
 Most common cause is that the Loot Table file is not actually at that location.
 Please let the mod author know about this so they can check to see if their Loot Table is correct.
```

[Blame](https://www.curseforge.com/minecraft/mc-mods/blame) is a mod that facilitates modding developers to find out their mistakes in the development.(_I think_)

**Love your mod and sorry for the machine translation.**

**Comment by Jusey1** [comment]
Ye'h, my kobolds don't have a drops loot table. This should, in theory, be an easy fix since I just need to add the loot tables but empty to this specific path and blame shouldn't be picking this up.

I never gave my kobolds a drop table because I wanted to discourage players killing them. So ye'h, I'll fix this for the next update. This issue shouldn't be crashing the game though at least.

**Comment by ZXLLlong** [comment]
I just saw that on the curseforge!
Thank you so much man!
