### ISSUE TITLE
Config Options

### ISSUE THREAD

**Issue by WACriminalG2** [Jusey1/Kobolds#2]
I saw that some folks have been having issues with spawn rates, biomes, etc. Rather than manually increasing the spawn rate or the biome selection, do you think you could externalize those settings into a config file so that we could tweak the numbers ourselves? It would also require less balance playtesting on your part, LOL.

**Comment by Jusey1** [comment]
I don't know how to do configs yet, so this will be on the backburner for now. I don't mind balancing/tweaking the numbers myself personally, and I think I got it in a good position right now.

**Comment by rodrigonramon** [comment]
It would be great to be able to blacklist biomes, because though I have not gone to look for underground settlements, the only ones I've seen are generating underwater in the ocean and are usually flooded and basically broken

**Comment by Jusey1** [comment]
This should not be happening at all because all vanilla ocean biomes are blacklisted by default for this reason.

**Comment by WACriminalG2** [comment]
I have to agree that a biome blacklist or something similar would be incredibly useful as a pack maker. I love the kobolds for the project I'm working on, but I'm using a custom world type and basically all the kobold structures are generating broken, and frequently floating in mid-air. I don't mind adding the kobolds back into my worldgen manually in my world type, I just need the option to exist to disable the mod's built-in worldgen.

**Comment by Jusey1** [comment]
Configs are coming in the 1.17.1 rework of the mod.

**Comment by GlowPon3** [comment]
Would be nice to add them to my other dimensions too.
