### ISSUE TITLE
Kobold + Kobold Axe = inconsistent results - clarification or bug?

### ISSUE THREAD

**Issue by VallenFrostweaver** [Jusey1/Kobolds#4]
Minecraft 1.16.5
Forge 36.1.2
Kobolds 1.2.3

When giving a regular kobold a kobold axe I am not always getting a warrior result. They take the axe and wait a bit then sometimes the axe disappears and they are still a kobold and will still accept trades. I have then tried giving another axe and they do the same. Testing on a group 3 I had 1 turn in 6 Axe trades (2 trades each). I have done this with Warrior and Enchanter types nearby too. If there is a chance of it happening then I understand but currently the mod page implies it is a standard.

**Comment by Jusey1** [comment]
Turning a kobold into a kobold warrior has a 25% chance to succeed.
