### ISSUE TITLE
Not working at all with Biomes O Plenty

### ISSUE THREAD

**Issue by leftbones** [Jusey1/Kobolds#4]
I'm testing this on 1.19.2 and the only other related world generation mods I have are Biomes O Plenty and Structory, as well as the assortment of YUNG's "Better" structure mods.

Using the `/locate` command I was able to "find" each of the kobold structures, but when teleporting there, it was just a standard biome with no structure or kobolds in sight. The only one that seemed to work was the desert dungeon. But, for example, when I teleported to the swamp dungeon, it was just a bog (Biomes O Plenty) and nothing else.

**Comment by Jusey1** [comment]
Did you check in Spectator mode?

**Comment by leftbones** [comment]
> Did you check in Spectator mode?

What do you mean by that? I've never used Spectator mode personally.

**Comment by Jusey1** [comment]
> > Did you check in Spectator mode?
> 
> What do you mean by that? I've never used Spectator mode personally.

Fly around in spectator mode to look underground? Kobold dens are underground so spectator mode helps a lot to find them for testing.

**Comment by Nycto97** [comment]
Well, I'm on 1.19.2, running 480 distinct mods between server and client, including Biomes O' Plenty, and locating a Kobolds structure and teleporting to it works just fine (as stated already they're underground)

![2023-12-01_06 09 11](https://github.com/Jusey1/Kobolds/assets/83367226/abb855fd-ef25-4d20-a104-108cca73dd95)
![image](https://github.com/Jusey1/Kobolds/assets/83367226/f7ccc055-df23-4b02-91e1-102e9f307a41)
![image](https://github.com/Jusey1/Kobolds/assets/83367226/f204d60b-dce7-4c65-b458-3cef6c9eb87f)
