### ISSUE TITLE
Supplementaries compatible problem

### ISSUE THREAD

**Issue by GauntAndreX8** [Jusey1/Kobolds#7]
Supplementaries added a new villager called the red wandering merchant and kobolds aren’t attacking him cause they think he is not a villager the supplementaries dev said is better if kobolds target all mobs with abstract villagers class instead of villager class
Do you think you can fix this plz

**Comment by Jusey1** [comment]
This is intended. Kobolds don't actually attack the vanilla Wandering Trader as well.
