### ISSUE TITLE
[Suggestion] Compatibility with Create: Trimmed

### ISSUE THREAD

**Issue by CherryPuppet** [Jusey1/Kobolds#9]
Create's materials and the Kobold template don't mesh together, the resulting armor piece has the missing texture colors. I think it would be neat if these were compatible.

![2024-07-03_16 38 37](https://github.com/Jusey1/Kobolds/assets/162679788/c6a234a5-fa45-4c44-a286-75893f11f6a2)

**Comment by Jusey1** [comment]
This can fixed in a resourcepack and should be done by the modpack author.
